### ISSUE TITLE
File Upload & Reordering categories

### ISSUE THREAD

**Issue by outrunthewolf** [moltin/php-sdk#19]
```
@ajsturrock: Hi Adam, just doing some extra work on the black crows site. We tried to add a new flow to category to add a cover image to category pages

Dave Ghijben [10:30 AM]
I added a new field to category

Dave Ghijben [10:30 AM]
with the following values

Dave Ghijben [10:31 AM]
name=cover
slug=cover
required=no
unique=no
type=File Upload
FIle formats= jpg, png, tif, jpeg, gif
maximum file size I left empty
```

```
Hi Dave, we'll need to make a push to our PHP SDK to fully support the file field type in forge, I'll speak to the team first thing tomorrow for you.
```

```
This is what rolled back to disable the file field type -

Removed POST support for files and data:
https://github.com/moltin/php-sdk/commit/532701dbf10961b93325002fc60b516d7dd8a433

Removed the field type from the form builder:
https://github.com/moltin/php-sdk/commit/939a0e8a62aae35e2961f73ec442c9f4ca978851
```

**Comment by zot24** [comment]
I got `Forge` working properly on my local machine connected with the live database, I rolledback the commits metioned above and I can add a new `file type field` to a `category flow` then go to the `entries` of that `category` and add one `img` per time, as well as in this case (because already existed a `field` `cover`) add a `cover` which was exactly what the user is requesting on this issue.

> Question: why this feature were removed? what was the issue with those commits?

<img width="1654" alt="create_field_file_type" src="https://cloud.githubusercontent.com/assets/678498/10197621/777ff9b2-6790-11e5-9434-19f1cd9b1d71.png">

<img width="1668" alt="flow_categories_fields" src="https://cloud.githubusercontent.com/assets/678498/10197623/77842078-6790-11e5-975b-d8f036bec889.png">

<img width="1664" alt="add_img_to_category" src="https://cloud.githubusercontent.com/assets/678498/10197698/c3efc03e-6790-11e5-8e4f-a33a3f17867f.png">

<img width="1255" alt="screen shot 2015-09-30 at 16 46 30" src="https://cloud.githubusercontent.com/assets/678498/10198191/d5b3b382-6792-11e5-9f98-9b3466955734.png">

**Comment by outrunthewolf** [comment]
> and add one img per time
 Can you add more than one image per time on the products and the categories?

**Comment by jHoldroyd** [comment]
Also could you try updating categories, as well as reordering them via Forge.

I have a feeling that one of the issues was that you could no longer reorder them, but I'm not 100% sure if we fixed this or not.

**Comment by zot24** [comment]
@outrunthewolf you can add more than one image from the `Images tab` but not from the `General tab`

@jHoldroyd updating works, so if you change something on the category it got saved on the database, however reordering the categories (if I understood what you mean with that, see picture below) is not working but it was not working before neither. If you go to the live forge and try to reordering them it just reorder them but when you refresh the appear on the previous position.

<img width="1212" alt="screen_shot_2015-10-01_at_10_00_44" src="https://cloud.githubusercontent.com/assets/678498/10216815/a9c35106-6823-11e5-94b7-47507a57585d.png">

**Comment by zot24** [comment]
@jHoldroyd ok just detected so issues when updating the `category` the cover just got deleted I'm having a look to that now

**Comment by zot24** [comment]
@jHoldroyd could you please confirm that being able to reordering the categories is something that have to be fixed?
